In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [4]:
(2 * np.ones((20,)))**np.arange(1,21) / np.arange(1,21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
i = np.arange(6)
np.sum(0.1**(3*i) * 0.2**(4*i))

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [5]:
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
X = np.random.random((5, 2))

r = np.sum(X ** 2, axis=1) ** 0.5
X[:,1] = np.arcsin(X[:,1]/r)
X[:,0] = r
X

array([[0.96252942, 0.75408265],
       [0.60336596, 1.14844665],
       [0.29947013, 0.22792802],
       [0.7907048 , 0.20129408],
       [0.8601339 , 0.09779107]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [13]:
X = np.random.random((10, 10))
ind = np.unravel_index(np.argmax(X), X.shape)
print(X, ind)

[[0.97175207 0.02443667 0.03515823 0.23848237 0.40314742 0.68045033
  0.47639888 0.85989349 0.17350041 0.25384562]
 [0.89725074 0.600365   0.76039947 0.611648   0.07123209 0.21366131
  0.08898144 0.40313345 0.14856633 0.9752697 ]
 [0.16219665 0.95024001 0.44530725 0.69501522 0.12504742 0.98217837
  0.84625735 0.88398632 0.28420121 0.89584705]
 [0.35697086 0.23068895 0.95939012 0.19728262 0.13158795 0.67184573
  0.21116317 0.32381812 0.72699084 0.77227838]
 [0.26381511 0.1146121  0.55766016 0.84522278 0.47989662 0.646041
  0.08455614 0.9914926  0.48004634 0.61809322]
 [0.37265984 0.69018064 0.71210822 0.85298473 0.29403295 0.72273433
  0.28624636 0.2191191  0.664787   0.19167851]
 [0.85952852 0.89062569 0.13356983 0.52566128 0.64009788 0.43625513
  0.8564116  0.384604   0.42958016 0.18608014]
 [0.30055536 0.50671161 0.22112027 0.70383857 0.80073236 0.24776679
  0.38595197 0.49562709 0.05421423 0.41889541]
 [0.56733086 0.99585857 0.09215139 0.82053784 0.73916273 0.16762421
  0.00518237 0

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [14]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
X, y, X[np.argmin(np.sum((X-y) ** 2, axis=1)), :]

(array([[0.40238575, 0.90287976],
        [0.8527239 , 0.57725482],
        [0.31391916, 0.73779258],
        [0.43201609, 0.9993561 ],
        [0.03559781, 0.59399149],
        [0.04692891, 0.84906177],
        [0.53571682, 0.1440046 ],
        [0.62015074, 0.79052048],
        [0.89673995, 0.36100306],
        [0.14505123, 0.1851931 ]]),
 array([[0.47747965, 0.55126696]]),
 array([0.31391916, 0.73779258]))

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [17]:
def f(x):
    if x < 0:
        return x ** 2 + 2*x + 6
    if 0 <= x <= 2:
        return x  + 6
    if x >= 2:
        return x ** 2 + 4*x-4

x = np.linspace(-3, 3, 100)
for i in x:
    print(f(i))

9.0
8.761248852157943
8.529843893480258
8.305785123966942
8.089072543617998
7.879706152433425
7.677685950413223
7.483011937557392
7.295684113865932
7.115702479338843
6.943067033976125
6.777777777777777
6.619834710743801
6.469237832874196
6.325987144168962
6.190082644628099
6.061524334251607
5.940312213039485
5.8264462809917354
5.719926538108356
5.620752984389348
5.528925619834711
5.444444444444445
5.367309458218549
5.297520661157025
5.235078053259871
5.179981634527089
5.132231404958677
5.0918273645546375
5.058769513314968
5.033057851239669
5.014692378328742
5.003673094582186
5.0
5.003673094582186
5.014692378328742
5.033057851239669
5.058769513314968
5.0918273645546375
5.132231404958678
5.179981634527089
5.235078053259872
5.297520661157025
5.367309458218549
5.444444444444445
5.528925619834711
5.620752984389348
5.719926538108356
5.8264462809917354
5.940312213039486
6.03030303030303
6.090909090909091
6.151515151515151
6.212121212121213
6.272727272727273
6.333333333333334
6.393939393939394

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [18]:
X = np.random.random((10, 10))

X = X.T - np.mean(X, axis=1).T
X = X.T

np.mean(X, axis=1)

array([-3.33066907e-17,  0.00000000e+00, -1.11022302e-17, -4.44089210e-17,
        4.44089210e-17,  8.88178420e-17,  0.00000000e+00,  2.22044605e-17,
       -2.22044605e-17, -3.33066907e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [19]:
X = np.random.normal(loc=5, scale=2., size=1000)
X.mean(), X.var()

(5.004693291703449, 4.039658647905301)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [24]:
x = np.ones((5, 5)) * np.arange(5)
x += x.T
x %= 5
x

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [28]:
def sample2(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    partial = np.repeat(np.cumsum(x), c).reshape((len(x), c)).astype("float32")
    val = s * np.random.random(c)
    partial -= val.T
    partial[partial >= 0] = 0
    
    return np.argmax(partial, axis=0)

sample2([50, 3, 1, 7, 20], 5)

array([0, 0, 0, 3, 4], dtype=int64)